version: '3.8'

volumes:
  prod_ollama_data: {}

services:
  rag_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: itips_rag_prod
    container_name: itips_rag_prod
    depends_on:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/app:z
      - /your/new/absolute/path/to/external_media:/media
    ports:
      - "1000:1000"
    env_file:
      - ./.envs/.production/.rag
      - ./.envs/.production/.postgres
      - ./.envs/.production/.redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 1000 --workers 4

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_rag_prod
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - prod_ollama_data:/root/.ollama

  ollama-pull:
    image: ollama/ollama:latest
    container_name: ollama_rag_prod_pull
    depends_on:
      - ollama
    entrypoint: /bin/sh
    environment:
      - OLLAMA_HOST=http://ollama:11434
    volumes:
      - .:/app:ro
    command: -c "sleep 10 && ollama pull llama3 && ollama create itips-brain -f /app/Modelfile"
